name: "PINGER: Test & Publish"

on:
  pull_request:
    branches:
      - master
    paths:
      - apps/pinger/**.*
      - packages/db/**.*

  push:
    branches:
      - master
    paths:
      - apps/pinger/**.*
      - packages/db/**.*
  workflow_dispatch:


defaults:
  run:
    working-directory: apps/pinger

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/setup-node@v3
        with:
          node_version: 20.2.0

      - uses: actions/checkout@master
      - run: npm i
      - run: npm test

  publish:
    runs-on: ubuntu-latest
    name: Publish

    needs: [test]

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@master
      - run: npm i -g wrangler
      - run: npm i

      - run: wrangler deploy --keep-vars -c ./wrangler.toml
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
